apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: go-exnumdqd 
  janus-idp.io/tekton: go-exnumdqd
  backstage.io/kubernetes-id: go-exnumdqd
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-exnumdqd
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml